version: "3.7"

services:
  n8n:
    restart: always
    image: n8nio/n8n
    ports:
      - "0.0.0.0:5678:5678"
    environment:
      - N8N_SECURE_COOKIE=FALSE
    volumes:
      - n8n_data:/home/node/.n8n
      - ./scripts:/scripts
volumes:
  n8n_data:
    external: true